### PR TITLE
Add support for units values

### LINKED ISSUE #8: Add units to ggplot
Using the units package we can associate (physical) units to quantities and guarantee that we only do arithmetic on compatible units. Plotting data with associated units, however, is cumbersome in ggplot. Can we make ggplot unit-aware?

### PR DESCRIPTION
**Pull request by thomasp85**
Fixes #8

This PR will add support for units from the units package. Scales will be automatically labelled and units can be changed in the scale rather than in the data itself.

### CODE REVIEW

**Comment by thomasp85** [comment]
The basic usage is that it automatically detects unit vectors and uses `scale_[x|y]_cunit()` as the default scale. This scale takes care of labelling axes with the unit. if multiple layers are drawn they are all converted to the units of the first layer and an error will be thrown if units are incompatible...

Lastly it is possible to change the axis units on the go with the unit argument, e.g.

```r
ggplot(d) + geom_point(aes(displacement, consumption))
```
rplot
```r
ggplot(d) + geom_point(aes(displacement, consumption)) + 
  scale_y_cunit(unit = with(ud_units, km/l))
```
rplot01

@mailund and @edzer can you comment on whether this is the feature set you had anticipated?

**Comment by edzer** [comment]
I can't get `ggforce` running; I'm getting
```
Installing ggforce
Installation failed: 'rcmd_safe_env' is not an exported object from 'namespace:callr'
```
Do I need some dev version of `callr`?

**Comment by thomasp85** [comment]
Odd. I'll look into it. Based on my examples can you tell me if I'm missing some points feature-wise

**Comment by edzer** [comment]
Looks good to me. Does everything invert when you do

    ggplot(d) + geom_point(aes(1 / displacement, 1 / consumption))

?

**Comment by thomasp85** [comment]
Will look tomorrow

**Comment by mailund** [comment]
It works great for me, and yes @edzer it also works with `aes(1 / displacement, 1 / consumption)`.

I noticed, though, that while this works

```r
gallon <- make_unit("gallon")
consumption <- mtcars$mpg * with(ud_units, mi/gallon)
displacement <- mtcars$disp * ud_units[["cm"]]^3
d <- data.frame(displacement = displacement, consumption = consumption)
ggplot(d) + geom_point(aes(displacement, consumption))
```

this will fail

```r
displacement <- mtcars$disp * ud_units[["in"]]^3
d <- data.frame(displacement = displacement, consumption = consumption)
ggplot(d) + geom_point(aes(displacement, consumption))
```

This isn't a problem with the `ggforce` code, as far as I can see, but with how the labels are constructed -- that code has problems with "in" as a unit. I will add an issue to `units`.

**Comment by thomasp85** [comment]
Yes I ran into this as well but thought I would report it somewhere else. Yu need to use `as.expression(str)` rather than `parse(text = str)` within `make_unit_label()` (I think - haven't tested it)...

Another funny thing. When making a unit with `make_unit()` the unit in the label gets surrounded by a parenthesis, while it does not if you use `with(ud_units, ...)`. Is this intentional?

**Comment by mailund** [comment]
It's not as simple as just using `as.expression`. That gives us labels that are the textual representation of the expressions, not the actual mathematical notation, so that is not the solution.

As for the other issue you mention, I am not sure I understand what you are saying. I don't get parenthesis in the labels if I make a unit with `make_label`.

```r
x <- with(ud_units, 1:5 * m)
y <- 1:5 * make_unit("m")
ggplot(data.frame(x = x, y = y)) + geom_point(aes(x, y))
```

rplot

```r
ggplot(data.frame(x = x, y = y)) + geom_point(aes(y, x))
```

rplot2

**Comment by edzer** [comment]
I think Thomas means this:
```
> make_unit("m sec-1")
1 (m sec-1)
> parse_unit("m sec-1")
1 m/sec
> 1/make_unit("m sec-1")
1 1/(m sec-1)
> 1/parse_unit("m sec-1")
1 sec/m
```
The reason for this is that the first allows for arbitrary (user-defined) units, which, when not put in parentheses, might lead to wrong expressions when combined with other units: the space acts as implicit multiply. Maybe we should always parse, if it is successful?

**Comment by mailund** [comment]
Ah, okay. I haven't used that notation myself so I didn't think of that. It probably makes sense to parse whenever we can.

I looked at the "inch thing" a little ... I think we can get around the problem by escaping all the units as "in" -> "`in`". That avoids conflicts with keywords while still allowing us to parse the expressions and thereby formatting them correctly when displaying the units in plots. I'll have a quick look at it.

**Comment by thomasp85** [comment]
Is udunits2 non-trivial to install on Linux machines? I can see that Travis fails to do it automatically... Pondering on whether I should merely suggest it in the Description rather than import it..?

**Comment by thomasp85** [comment]
In terms of the parenthesis I was generally referring to the situation that occurs here:
rplot02

rplot03

Notice that *km/l* gets surrounded by parenthesis while *mi/gallon* does not...

**Comment by edzer** [comment]
Thomas, does ggforce have problems installing on ubuntu? I keep seeing:
```
> devtools::install_github("thomasp85/ggforce")
Downloading GitHub repo thomasp85/ggforce@master
from URL https://api.github.com/repos/thomasp85/ggforce/zipball/master
Installing ggforce
trying URL 'https://cran.uni-muenster.de/src/contrib/Rcpp_0.12.8.tar.gz'
Content type 'application/x-gzip' length 2435852 bytes (2.3 MB)
==================================================
downloaded 2.3 MB

Installing Rcpp
Installation failed: 'rcmd_safe_env' is not an exported object from 'namespace:callr'
Installation failed: 'rcmd_safe_env' is not an exported object from 'namespace:callr'
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.2.1           R6_2.2.0             tools_3.3.2         
 [4] withr_1.0.2          curl_2.2             highlight_0.4.7     
 [7] memoise_1.0.0        knitr_1.15           callr_1.0.0         
[10] pkgload_0.0.0.9000   digest_0.6.10        pkgbuild_0.0.0.9000 
[13] devtools_1.12.0.9000
> 
```
meaning, I can't try out your units stuff. Looking at it, pls try `scale_y_unit =  make_unit("km")/make_unit("l")`, to get rid of the parenthesis. (We might be able to get rid of this in package units later on; right now `parse_unit("km l-1")` parses correctly, but you can't currently rely on parse_unit to parse all units correctly, see this [issue](https://github.com/edzer/units/issues/18).)

Re: your udunits on travis/linux, yes it needs an external library, see [this](https://github.com/edzer/units/blob/master/.travis.yml) travis file for an easy solution.

Great that you integrated this PR in master, we can now advertise it in the [vignette / R Journal draft MS](https://cran.rstudio.com/web/packages/units/vignettes/measurement_units_in_R.pdf), which is close to acceptance.

**Comment by mailund** [comment]
I don't have an ubuntu box any longer either so I can't test it, sorry. It all works very nicely on macOS though

**Comment by edzer** [comment]
My installation problems went away after reinstalling `devtools`, or installing by cloning first and then installing by hand.

**Comment by thomasp85** [comment]
When are you planning to release 0.3.1 on CRAN? I'm importing `make_unit_label()` in ggforce so I cannot release ggforce before that has been included in the CRAN version...

**Comment by edzer** [comment]
I submitted it (version 0.4-0) to CRAN just before dinner, a couple of hours ago. I acknowledged your contribution, and added a ggplot to the vignette that's under review for the R Journal.

**Comment by thomasp85** [comment]
Fantastic - can you give me a heads-up when it is up?

**Comment by edzer** [comment]
Will do!

**Comment by edzer** [comment]
0.4-0 is on CRAN now: https://cran.r-project.org/web/packages/units/index.html

**Comment by edzer** [comment]
Please let me know when ggforce is up, so I can cite it in our R Journal MS.

**Comment by thomasp85** [comment]
Will do - just need to write the release notes and send to CRAN

**Pull request merged**
