### PR TITLE
New parameter 'seed' and code cleanup on geom_sina(). 

### LINKED ISSUE #90: geom_sina acts differently than geom_jitter or geom_violin with distribution of ints
I think this is intended behavior, but it seems like a missed opportunity?  When distribution is clustered on the y axis, as in a distribution of ints, geom_jitter shifts some points vertically as well as horizontally. geom_violin also "spreads" the values at each point so that one can see the distribuiton. 
 geom_sina, though, just ends up with lines of dots at each exact point. 

```{r}
library(tidyverse)
library(ggforce)

# create int version of area
midwest$area_ints <- (midwest$area * 100) %>% floor()

ggplot(midwest, aes(state, area_ints)) + 
  geom_sina() + geom_jitter(color="red")
```

or:

```{r}
ggplot(midwest, aes(state, area_ints)) + 
  geom_violin() + geom_sina()
```

I guess I was expected geom_sina to jitter vertically as well, basically shaping the dot cloud to match geom_violin?

### PR DESCRIPTION
**Pull request by sidiropoulos**
Fixes #90
I reset my master fork and recreated the previous pull request.

### CODE REVIEW

**Comment by thomasp85** [comment]
I generally hate having seed as an argument. It will affect all code that runs afterwards, but this is not apparent to the user, who often thinks that it only affects the code within the function... setting `set.seed(1)` before plotting achieves the same but makes it obvious that the global state is changed.

Is there a very real reason to have it as an argument?

**Comment by sidiropoulos** [comment]
It mainly serves reproducibility purposes. 
What do you mean by "will affect all code that runs after the function"?

I tried consecutive calls of geom_sina, one with seed and one without and there is no memory of the seed in the second one. 

```
p <- ggplot(midwest, aes(state, popdensity)) + scale_y_log10()
p + geom_sina(seed = 1) + geom_sina(color = "2")
```

image

**Comment by thomasp85** [comment]
The memory is in how it affects all subsequent sampling.

```r
p <- ggplot(midwest, aes(state, popdensity)) + scale_y_log10()
p + geom_sina(seed = 1) + geom_sina(color = "2")
sample(10)
```

If you call the above block repeatedly, you'll notice that the sample call will always return the same sequence, even though it is supposed to be random. This will confuse people that only expect the seed argument to affect the produced plot and not code that follows it. On the other hand, the following block makes it obvious that you are meddling with the global state:

```r
set.seed(10)
p <- ggplot(midwest, aes(state, popdensity)) + scale_y_log10()
p + geom_sina() + geom_sina(color = "2")
sample(10)
```

and people will not be surprised that all code will be affected by it.

So, if the seed argument is to remain it will need to be implemented in such a way that it does not affect the global environment. One way of achieving that is to getting a new seed prior to setting it so your code will be:

```r
if (!is.null(params$seed)) {
  new_seed <- sample(.Machine$integer.max, 1)
  set.seed(params$seed)
  on.exit(set.seed(new_seed))
}
```

Another way would simply be to educate users about using `set.seed()` when they want to ensure reproducibility....

**Comment by sidiropoulos** [comment]
I see, thanks for clarifying that. I followed the first of your suggestions and removed the parameter completely, as it seems like the more neat solution.

**Comment by thomasp85** [comment]
Have you been requested to add it? In that case you should probably forward the `set.seed()` solution to them

**Pull request merged**
