### PR TITLE
Update version and tidy-up description

### PR DESCRIPTION
**Pull request by JBGruber**
Thanks @thomasp85 for creating this wonderful package!

I had some problems with the GitHub version since the version number was older than the one on CRAN. I fixed that and while I was there updated the date and added minimum version numbers to your `Imports` (which is recommended [here](http://r-pkgs.had.co.nz/description.html)).

`R CMD check` told me that `ggrepel` is unnecessary now, so I removed it.

Additionally, `.travis.yml` and `appveyor.yml` are now in `.Rbuildignore` which fixes some warnings in `R CMD check`.

### CODE REVIEW

**Comment by JBGruber** [comment]
`lintr` also recommends dropping the `Date` entirly. If you don't plan to do anything with it in the future that might also make sense.

**Comment by thomasp85** [comment]
How have you determined the version dependencies for the packages?

**Comment by JBGruber** [comment]
I usually just follow the advice here: http://r-pkgs.had.co.nz/description.html

> Generally, it’s always better to specify the version and to be conservative about which version to require. Unless you know otherwise, always require a version greater than or equal to the version you’re currently using.

However, since you support  `R` (>= 3.3.0) and `grDevices`, `grid` and `stats` use the same version number as `R` itself, I used that version for them. 

For `gtable`, `MASS`, `polyclip` and `tweenr` I looked up the versions available at the time `R` 3.3.0 was released.

`scales` (>= 0.5.0) is necessary for `ggplot2` (>= 3.0.0). For `rlang` I choose 0.3.0 since the API in earlier releases seems different.

I then ran a `R` 3.3.0 docker container, installed the exact versions listed in Imports and checked if the new version of ggforce was still running. I knitted the Visual_Guide vignette as a test case.

You already implemented the changes I found important (correct version number). So feel free to close if you don't want the minimal version numbers.

**Comment by thomasp85** [comment]
Thanks - I'm going to close since I know most of these dependencies and what they use. Thanks for the effort still!

**Pull request closed without merging**
