### PR TITLE
Add stat_err to draw intervals of points in x- and y- directions

### PR DESCRIPTION
**Pull request by atusy**
This PR implements `stat_err()` which draws intervals of points in x- and y- directions.
A following example shows that `stat_err()` appears to be more intuitive than the combination of `geom_errorbar` and `geom_errorbarh`.

image

```r
library(ggplot2)
library(ggforce)

x <- 1:3
xmin <- x - 2.5
xmax <- x + 2.5
d <- data.frame(x = x, y = x, xmin = xmin, ymin = xmin, xmax = xmax, ymax = xmax, color = as.factor(x))
g <- ggplot(d) +
  aes(x = x, y = y, xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, color = color)

g + stat_err(size = 5) + ggtitle("stat_err()")
g+ geom_errorbar(size = 5) + geom_errorbarh(size = 5) + ggtitle("geom_errorbar() + geom_errorbarh()")
```

### CODE REVIEW

**Comment by thomasp85** [comment]
It's been a while - do you still want this in here or have it found another home?

**Comment by atusy** [comment]
Yes, I'm glad if you merge this PR.
I have been using the function in my private package because I have no ideas to place this in somewhere else.

**Comment by atusy** [comment]
I rebased to current main

**Comment by thomasp85** [comment]
Thanks

**Pull request merged**
