### PR TITLE
Added geom_sina

### PR DESCRIPTION
**Pull request by sidiropoulos**
First draft of geom_sina. I adjusted the code from https://github.com/sidiropoulos/ggplot2 based on the other geoms in ggforce. 

A "dark" point is that when I wrote the function to be integrated directly in ggplot2 I was using the functions in [bin.R](https://github.com/hadley/ggplot2/blob/master/R/bin.R) which are not exported, so I copy-pasted functions stat_sina is using. We can work around this if it's an issue.

### CODE REVIEW

**Comment by thomasp85** [comment]
Since it went through quite a thorough review process in ggplot2 I think I'm just going to merge and then see if there's any small changes I would like to do - thanks

**Comment by thomasp85** [comment]
BW can I get you to add a section to the vignette? (just in a new PR)

**Comment by sidiropoulos** [comment]
Yes, I'm on it. Can you see it as a subsection of transformations or separate?

**Comment by thomasp85** [comment]
Separate

**Pull request merged**
